### PR TITLE
fix: typo for `cleanUrls: true` on Vercel

### PR DESCRIPTION
**Pull request by styfle**
I tested this this by deploying with `{ "cleanUrls": true }`. I think this was just a typo in the readme.

- Demo: https://static-51pmxlq6o-uncurated-tests.vercel.app
- Source: https://vercel.com/uncurated-tests/static/5hpt5czKTWgstPpC68eeTMfXVMj1/source?f=src%2Fvercel.json

### CODE REVIEW

**Comment by slorber** [comment]
Ohhh I remember now: I used one branch per `vercel.json` config file.

The appropriate branch: https://github.com/slorber/trailing-slash-guide/blob/vercel-cleanurls-true-trailingslash-undefined/static/vercel.json

It looks wired correctly:

CleanShot 2023-08-03 at 17 48 31@2x


Note I explicitly use `trailingSlash: undefined`, can it have any impact?


---

This is really weird, my deployment shows a preview screenshot that looks like your results, but it's not what I see in practice after navigating to this deployment locally!

https://vercel.com/trailing-slash-team/vercel-cleanurls-true-trailingslash-undefined shows:

CleanShot 2023-08-03 at 17 50 50@2x

And this other url https://vercel.com/trailing-slash-team/vercel-cleanurls-true-trailingslash-undefined/3Xw7ZAyiKSbZwFawchhK9k1f8nAb shows:

CleanShot 2023-08-03 at 17 52 15@2x

**Comment by styfle** [comment]
This looks like a typo too: https://github.com/slorber/trailing-slash-guide/blob/252d26d0466357e98fd3c53aec0680a8bae778ff/static/vercel.json#L4

It has the string `"undefined"` instead of the actual value of `undefined`

**Comment by styfle** [comment]
@slorber Can you approve the deployments in this PR to confirm that the previews work as expected now?

**Comment by slorber** [comment]
Ahhh 🤯 good catch!

Thanks, that now works!

https://vercel-cleanurls-true-trailingslash-undefined.vercel.app/

CleanShot 2023-08-03 at 19 02 40

Not exactly the results you updated in this PR: we still have some server redirects (expected IMHO)


Also: I updated both deployments with `"undefined"`, so both might have a problem, not just this one.

Also, the table is displayed there too: https://github.com/slorber/trailing-slash-guide/blob/main/docs/Hosting-Providers.md

--- 

Normally the full Markdown table is automatically generated with code in the console if you go on the deployment index: https://vercel-cleanurls-true-trailingslash-undefined.vercel.app/

It seems they shut down the CORS proxy I was using: https://github.com/slorber/trailing-slash-guide/blob/main/static/index.html#L202

I can fix it so that we don't have to manually edit again, but do you know a good free CORS proxy I could rely on?

**Comment by styfle** [comment]
> do you know a good free CORS proxy I could rely on?

You could try this one: https://github.com/josmas/vercel-proxy

Demo: http://vercel-proxy.vercel.app

**Comment by slorber** [comment]
Probably not the most robust CORS impl but it seems to work:
- https://github.com/slorber/vercel-proxy/blob/master/api/index.js
- https://slorber-cors-proxy.vercel.app/api?url=https://trailing-slash-guide-default.netlify.app/folder/

Will try to update it on this repo tomorrow 👍

**Comment by slorber** [comment]
Table regeneration fixed 👍 thanks for the fix

**Pull request merged**
